spring.application.name=cms-springboot
spring.datasource.url=jdbc:sqlite:database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf config
spring.thymeleaf.cache=false

# Server Port
server.port=8080

# File Upload Max Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Web MVC config to serve uploads statically
upload.dir=public/uploads/
